### ISSUE TITLE
Model inputs and outputs

### ISSUE THREAD

**Issue by hoiiranoi** [Z-Zheng/Changen#1]
I want to make the model output t1 before the change, t2 after the change, and the label image label. However, according to the code provided, it seems that only the final change map is output. How can I achieve the output of the three images I want?
![Figure_1](https://github.com/Z-Zheng/Changen/assets/150221083/71941461-54c6-4a07-b306-1b6b967cd206)
![屏幕截图 2023-11-24 233024](https://github.com/Z-Zheng/Changen/assets/150221083/f59a1b82-875d-41a8-b804-16c275c32050)

**Comment by Z-Zheng** [comment]
The released model was only trained for building change detection, though it is a multi-task architecture. So, it only yielded binary change prediction. If you want to obtain the temporalwise semantic prediction, you can consider training this model with multi-task supervision.
